### ISSUE TITLE
Fails to connect to non-HTTPS server

### ISSUE THREAD

**Issue by fuchunic** [bwesterb/twittermost#10]
Mattermost ver 5.3.1
whent start ./twittermost

Get error

2018/10/04 11:30:58 Connected to mattermost server at http://127.0.0.1:8065
2018/10/04 11:30:58 mattermost: logged in as chatbot
2018/10/04 11:30:58 Connecting websocket to listen for events ...
2018/10/04 11:30:58   failed: NewWebSocketClient: model.websocket_client.connect_fail.app_error, tls: oversized record received with length 20527
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=1 addr=88 pc=94422000462953]

goroutine 27 [running]:
panic
        ../../../src/libgo/go/runtime/panic.go:554
main.func1
        /home/user/go/src/github.com/bwesterb/twittermost/main.go:178
created by main.Bot.setupMattermost
        /home/user/go/src/github.com/bwesterb/twittermost/main.go:176 +4382

**Comment by bwesterb** [comment]
Twittermost expects `https` instead of plain `http`.
