### ISSUE TITLE
trust username triggers panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by UHHNieselregen** [bwesterb/twittermost#12]
Hey i just installed the Bot and cant use the `trust username` Command. When i use it i get the following error:

goroutine 29 [running]:
main.(*Bot).handleTrust(0xc0000a26e0, 0xc0003d5400, 0xc0003d8d70, 0x1, 0x1)
	/go/path/go/src/twittermost/main.go:462 +0x11a
main.(*Bot).handleWebSocketEvent(0xc0000a26e0, 0xc0004a7860)
	/go/path/go/src/twittermost/main.go:256 +0x3e9
main.(*Bot).setupMattermost.func1(0xc0000a26e0)
	/go/path/go/src/twittermost/main.go:181 +0x79
created by main.(*Bot).setupMattermost
	/go/path/go/src/twittermost/main.go:175 +0x4

any ideas whats gone wrong? And this might come from an error during the Installation, i wasnt able to just use the `go get github.com/bwesterb/twittermost` commend he kept telling me `can't load package: package: no buildable Go source files`, so i just got the folder usig git and then used `go build twittermost` with seemed to work. The Bot runs and i can use most of the commands but cant use the trust command? You got any ideas? Is it my Setup? or any kind of incompatibility?

**Comment by bwesterb** [comment]
Hi, thanks for reporting.  I'm trying to reproduce the issue now.

**Comment by bwesterb** [comment]
Could you check current master?

**Comment by UHHNieselregen** [comment]
Just got it and it works like a charm! Thank you alot!
