### ISSUE TITLE
Maybe note this requires API v3?

### ISSUE THREAD

**Issue by rocketnova** [bwesterb/twittermost#7]
I ran into a lot of errors getting this set up until I discovered that it required API v3. I got a bunch of these errors: `API version 3 has been disabled on this server. Please use API version 4.` Once I allowed API v3 on my mattermost instance, I was able to use it. It might be helpful to include a note about this requirement in the README.

Thanks!
Rocket

**Comment by bwesterb** [comment]
Twittermost uses the v4 api since 4e9124da96c2d489afbc15bd21f18540379e921c .  Did you update already?

**Comment by bwesterb** [comment]
( `go get -u github.com/bwesterb/twittermost` )

**Comment by rocketnova** [comment]
Ah I see. I'm using your Dockerfile and built the image yesterday. Shouldn't that have pulled the latest version?

**Comment by bwesterb** [comment]
@drallgood Do you have a clue?

**Comment by drallgood** [comment]
@rocketnova If you built it yesterday (and you did a git pull before doing so) I think it should already be using APIv4.
Can you please double check that this is the case (i.e. you built the image based on an up-to-date git repo and the running docker image is that same image you just built?)

**Comment by rocketnova** [comment]
Just git-pulled (already up to date) and rebuilt my docker image using your Dockerfile again today. Confirmed that I'm using the newly built image. Still getting the same error when API v3 is turned off. :( Here's the error: `/api/v3/users/websocket:ServeHTTP code=501 rid=REDACTED uid= ip=REDACTED API version 3 has been disabled on this server. Please use API version 4. See https://api.mattermost.com for details. [details: ]`

**Comment by drallgood** [comment]
Damn.. forgot about the web socket. That one was still using v3.
Should be fixed now

**Comment by bwesterb** [comment]
@drallgood Thanks for the fix.
@rocketnova Thanks for reporting and perservering!

**Comment by rocketnova** [comment]
@drallgood @bwesterb Thank you!
